name: Server Logger Bot

on:
  schedule:
    - cron: '*/15 * * * *' # Jalan tiap 15 menit
  workflow_dispatch: # Bisa dijalankan manual

jobs:
  log-status:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd gt-logger
          npm install

      - name: Run Logger
        run: |
          cd gt-logger
          node logger.js
